import { AudioTrack } from './types';

export const audioTracks: AudioTrack[] = [
  {
    id: 'bg1',
    src: '/audio/BG1.wav',
    startFrame: 'white(intro).jpg',
    stopFrame: 'city0.jpg',
    volume: 0.5,
    fadeEffect: true,
    loop: true,
  },
  {
    id: 'fx1',
    src: '/audio/FX1.wav',
    startFrame: 'loading0.jpg',
    stopFrame: 'loading5.jpg',
    volume: 1,
    fadeEffect: false,
    loop: true,
  },
  {
    id: 'bg2',
    src: '/audio/BG2.wav',
    startFrame: 'intro.gif',
    stopFrame: 'city0.jpg',
    volume: 0.7,
    fadeEffect: true,
    loop: true,
  },
//bg3
//bg4_1
{
  id: 'fx2',
  src: '/audio/FX2.wav',
  startFrame: 'arif22.jpg',
  stopFrame: 'arif25.jpg',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'fx3',
  src: '/audio/FX3.wav',
  startFrame: 'arif29.jpg',
  stopFrame: 'arif31.jpg',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'bg5',
  src: '/audio/BG5.wav',
  startFrame: 'arif22.jpg',
  stopFrame: 'home1.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg6',
  src: '/audio/BG6.wav',
  startFrame: 'arif22.jpg',
  stopFrame: 'mgm1.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'fx4',
  src: '/audio/FX4.wav',
  startFrame: 'arif-fc1-fx4.PNG',
  stopFrame: 'arif-fc1-stopfx.PNG',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'fx5',
  src: '/audio/FX5.wav',
  startFrame: 'home1.PNG',
  stopFrame: 'home7.PNG',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'bg8_1',
  src: '/audio/BG8.wav',
  startFrame: 'home9.PNG',
  stopFrame: 'white.jpg',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg18_1',
  src: '/audio/BG18.wav',
  startFrame: 'home9.PNG',
  stopFrame: 'white.jpg',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg8_2',
  src: '/audio/BG8.wav',
  startFrame: 'mom1.PNG',
  stopFrame: 'arifcf.gif',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'fx6',
  src: '/audio/FX6.wav',
  startFrame: 'mom2.PNG',
  stopFrame: 'arifcf.gif',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'bg18_2',
  src: '/audio/BG18.wav',
  startFrame: 'gmom1.PNG',
  stopFrame: 'gone1.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg19_1',
  src: '/audio/BG19.wav',
  startFrame: 'gmom1.PNG',
  stopFrame: 'arifcf.gif',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'fx7',
  src: '/audio/FX7.wav',
  startFrame: 'gmom2.PNG',
  stopFrame: 'arifcf.gif',
  volume: 0.7,
  fadeEffect: false,
  loop: false,
},
{
  id: 'bg8_3',
  src: '/audio/BG8.wav',
  startFrame: 'mgm1.PNG',
  stopFrame: 'mgm5.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg18_3',
  src: '/audio/BG18.wav',
  startFrame: 'mgm1.PNG',
  stopFrame: 'mgm5.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg19_2',
  src: '/audio/BG18.wav',
  startFrame: 'mgm1.PNG',
  stopFrame: 'mgm5.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg4_2',
  src: '/audio/BG4.wav',
  startFrame: 'mgm5.PNG',
  stopFrame: 'arif-sad1.PNG',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
{
  id: 'bg7_1',
  src: '/audio/BG7.wav',
  startFrame: 'arif-sad1.PNG',
  stopFrame: 'arif-sml1.png',
  volume: 0.7,
  fadeEffect: true,
  loop: true,
},
];